version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - client
    volumes:
    - media-volume:/srv/data/media
  client:
    image: mreddy3/rescueme:1.6
    tty: true
    ports:
      - 8081:80
  mongo:
    image: mongo
    volumes:
    - data-volume:/srv/data/db
volumes:
  data-volume:
  media-volume: